### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by glidbjorg** [Syiana/SUI#24]
Hello!

Im very fond of your addon and awaiting the 10.0 release!
Is it possible to add these features to the addon?:
- Tab will only target enemy players in pvp instances
- Sorting of group members

Currently these features are covered by the addons RETabbinder and SortGroup respectively, but they are not working properly and im not sure they will get proper updates.

My apologies if this is the wrong place to submit this.

Thank you in advance!

**Comment by muleyo** [comment]
Tab-Targeting for enemy players already exists.

And for sorting group members there's an addon called SortGroup.

**Comment by glidbjorg** [comment]
> 

Yes it exists in the settings, but then it doesnt function in open world and PvE. It is very handy to have an addon make it so you only tab to players when inside a pvp instance.
And SortGroup is bugging out for me even though its updated, and has always been kinda buggy.
Anyways it was just a suggestion :)

**Comment by muleyo** [comment]
> > 
> 
> Yes it exists in the settings, but then it doesnt function in open world and PvE. It is very handy to have an addon make it so you only tab to players when inside a pvp instance.

If you enable "Tab Binder" in SUI, it will always change to "Only Target Enemy Player" if you are in a PVP combat (which actually makes sense). So that way it works everywhere. So whenever you leave PVP combat, it will change back to the normal TAB behavior.

> > 
> 
> And SortGroup is bugging out for me even though its updated, and has always been kinda buggy. Anyways it was just a suggestion :)

SortGroup is working fine for me at the moment, it does what it should do. Place yourself at the very top or bottom. :)
